rabbitmq:
  auth:
    password: CHANGEME
  extraSecrets:
    load-definition:
      load_definition.json: |
        {
          "users": [
            {
              "name": "rmuser",
              "password": "rmpassword",
              "tags": "administrator"
            }
          ],
          "vhosts": [
            {
              "name": "/"
            }
          ]
        }
  loadDefinition:
    enabled: true
    existingSecret: load-definition
  extraConfiguration: |
    load_definitions = /app/load_definition.json